# Generated by Django 4.2.3 on 2023-07-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.ImageField(blank=True, default='images/default_playlist.PNG', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usercreatedsong',
            name='artist',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usercreatedsong',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
