# Generated by Django 4.2 on 2023-07-23 20:29

from django.db import migrations, models
import spotclone_project.music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_playlist_image_alter_playlist_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercreatedsong',
            name='duration',
        ),
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercreatedsong',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=spotclone_project.music.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='usercreatedsong',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
